/******************************************************************
Inicio.java
Autor: Arturo Argueta, Bryan España, Adrian Fulladolsa, Diego Valdez
Última modificación: 2021-10-01
Ventana de Inicio de sesión
******************************************************************/
package Vistas;

/**
 *
 * @author inmar
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoUsuarioRegistro = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        LOG = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        LoginWarner = new javax.swing.JLabel();
        REG = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Rname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RID = new javax.swing.JTextField();
        user = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        Register = new javax.swing.JButton();
        Cleaner = new javax.swing.JButton();
        RWarning = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Path = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SendPath = new javax.swing.JButton();
        Messenger = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOG.setBackground(new java.awt.Color(255, 255, 255));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(51, 51, 51));
        Login.setText("Inicio de Sesion");

        Clean.setBackground(new java.awt.Color(255, 255, 255));
        Clean.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Clean.setForeground(new java.awt.Color(51, 51, 51));
        Clean.setText("Limpiar");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ingresar Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Ingresar ID Personal");

        name.setBackground(new java.awt.Color(255, 255, 255));

        ID.setBackground(new java.awt.Color(255, 255, 255));

        LoginWarner.setForeground(new java.awt.Color(153, 0, 0));
        LoginWarner.setText("yo soy el warning :v");

        javax.swing.GroupLayout LOGLayout = new javax.swing.GroupLayout(LOG);
        LOG.setLayout(LOGLayout);
        LOGLayout.setHorizontalGroup(
            LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGLayout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addGroup(LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGLayout.createSequentialGroup()
                        .addComponent(LoginWarner)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LOGLayout.createSequentialGroup()
                            .addComponent(Login)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Clean, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGLayout.createSequentialGroup()
                            .addGroup(LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ID)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(3, 3, 3))))
                .addGap(41, 41, 41))
        );
        LOGLayout.setVerticalGroup(
            LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clean, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(LoginWarner)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio Sesion", LOG);

        REG.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Ingresar Nombre");

        Rname.setBackground(new java.awt.Color(255, 255, 255));
        Rname.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ingresar ID Personal");

        RID.setBackground(new java.awt.Color(255, 255, 255));
        RID.setForeground(new java.awt.Color(0, 0, 0));

        user.setBackground(new java.awt.Color(255, 255, 255));
        tipoUsuarioRegistro.add(user);
        user.setForeground(new java.awt.Color(51, 51, 51));
        user.setText("Empleado");

        tipoUsuarioRegistro.add(admin);
        admin.setForeground(new java.awt.Color(51, 51, 51));
        admin.setText("Administrador");

        Register.setBackground(new java.awt.Color(255, 255, 255));
        Register.setForeground(new java.awt.Color(51, 51, 51));
        Register.setText("Registrarse");

        Cleaner.setBackground(new java.awt.Color(255, 255, 255));
        Cleaner.setForeground(new java.awt.Color(51, 51, 51));
        Cleaner.setText("Limpiar");
        Cleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanerActionPerformed(evt);
            }
        });

        RWarning.setForeground(new java.awt.Color(204, 0, 0));
        RWarning.setText("yo soy el warning");

        javax.swing.GroupLayout REGLayout = new javax.swing.GroupLayout(REG);
        REG.setLayout(REGLayout);
        REGLayout.setHorizontalGroup(
            REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGLayout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addGroup(REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user)
                    .addComponent(admin)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, REGLayout.createSequentialGroup()
                            .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Cleaner, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addComponent(RID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Rname, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(68, 68, 68))
        );
        REGLayout.setVerticalGroup(
            REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rname, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin)
                .addGap(15, 15, 15)
                .addGroup(REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cleaner, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(RWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrarse", REG);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Path.setBackground(new java.awt.Color(255, 255, 255));
        Path.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ingresar el Directorio Donde se Almacenan los datos");

        SendPath.setBackground(new java.awt.Color(255, 255, 255));
        SendPath.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        SendPath.setForeground(new java.awt.Color(51, 51, 51));
        SendPath.setText("enviar");

        Messenger.setForeground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Path, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(SendPath, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Messenger))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(Messenger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Path, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SendPath, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Directorio", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // limpiar las casillas
        ID.setText("");
        name.setText("");
    }//GEN-LAST:event_CleanActionPerformed

    private void CleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanerActionPerformed
        // limpiar casillas de registro de sesion
        RID.setText("");
        Rname.setText("");
    }//GEN-LAST:event_CleanerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clean;
    private javax.swing.JButton Cleaner;
    private javax.swing.JTextField ID;
    private javax.swing.JPanel LOG;
    private javax.swing.JButton Login;
    private javax.swing.JLabel LoginWarner;
    private javax.swing.JLabel Messenger;
    private javax.swing.JTextField Path;
    public javax.swing.JPanel REG;
    private javax.swing.JTextField RID;
    private javax.swing.JLabel RWarning;
    private javax.swing.JButton Register;
    private javax.swing.JTextField Rname;
    private javax.swing.JButton SendPath;
    private javax.swing.JRadioButton admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name;
    private javax.swing.ButtonGroup tipoUsuarioRegistro;
    private javax.swing.JRadioButton user;
    // End of variables declaration//GEN-END:variables
public javax.swing.JButton Login(){//devuelve la clase del boton de inicio de sesión
    return Login; 
}
public String LoginData(){//devolver el valor de los campos presionados
    return String.join(":", name.getText(),ID.getText());
}
public void Warning(String w){//mostrar el error u mensaje al usario en la gui
    LoginWarner.setText(w);
}
public javax.swing.JButton Register(){//devuelve la clase del boton de registrar sesión
    return Register; 
}
public void RWarning(String a){//mostrar el error u mensaje al usario en la gui en la pestaña de registro
    RWarning.setText(a);
}
public String[] NewUser(){//devuelve el array con los datos del nuevo usuario
    String[] data = new String[3];
    if(admin.isSelected()){//si se eleigio que sea administrador
        data[2] = String.valueOf(true);//true = administrador
    }else if(user.isSelected()){
        data[2] = String.valueOf(false);//false = usuario normal
    }
    data[0] = Rname.getText();//obtener valor de su nombre
    data[1]= RID.getText();//obtener valor de su ID
    
    return data;
}
public String getPath(){//obtener el directorio
    return Path.getText();
}
public javax.swing.JButton getSend(){//obtener la instancia del botón, le sirve al controlador
    return SendPath; 
}
public void setMessenger(String a){//advertencia o mensaje en el apartado de enviar directorio
    Messenger.setText(a);
}
}

