/*
Ventana de Inicio de sesión
 */
package Vistas;

/**
 *
 * @author inmar
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoUsuarioRegistro = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        LOG = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        LoginWarner = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        REG = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Rname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RID = new javax.swing.JTextField();
        user = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        Register = new javax.swing.JButton();
        Cleaner = new javax.swing.JButton();
        RWarning = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Path = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SendPath = new javax.swing.JButton();
        Messenger = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOG.setBackground(new java.awt.Color(255, 251, 246));
        LOG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(51, 51, 51));
        Login.setText("Entrar");
        Login.setToolTipText("");
        LOG.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, 30));

        Clean.setBackground(new java.awt.Color(255, 255, 255));
        Clean.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Clean.setForeground(new java.awt.Color(51, 51, 51));
        Clean.setText("Limpiar");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });
        LOG.add(Clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 100, 30));

        jLabel1.setBackground(new java.awt.Color(255, 251, 246));
        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ingresar Nombre");
        LOG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 251, 246));
        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Ingresar ID Personal");
        LOG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        name.setBackground(new java.awt.Color(255, 251, 246));
        name.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        LOG.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 238, 30));

        ID.setBackground(new java.awt.Color(255, 251, 246));
        ID.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(51, 51, 51));
        LOG.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 238, 30));

        LoginWarner.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        LoginWarner.setForeground(new java.awt.Color(153, 0, 0));
        LOG.add(LoginWarner, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 320, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Sesion2.png"))); // NOI18N
        LOG.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 360, 530));

        jLabel8.setBackground(new java.awt.Color(255, 251, 246));
        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Iniciar Sesión");
        LOG.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jTabbedPane1.addTab("Inicio Sesion", LOG);

        REG.setBackground(new java.awt.Color(255, 251, 246));
        REG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 251, 246));
        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Ingresar Nombre");
        REG.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        Rname.setBackground(new java.awt.Color(255, 251, 246));
        Rname.setForeground(new java.awt.Color(0, 0, 0));
        REG.add(Rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 212, 30));

        jLabel4.setBackground(new java.awt.Color(255, 251, 246));
        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ingresar ID Personal");
        REG.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        RID.setBackground(new java.awt.Color(255, 251, 246));
        RID.setForeground(new java.awt.Color(0, 0, 0));
        REG.add(RID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 212, 30));

        user.setBackground(new java.awt.Color(255, 251, 246));
        tipoUsuarioRegistro.add(user);
        user.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(51, 51, 51));
        user.setText("Empleado");
        REG.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        admin.setBackground(new java.awt.Color(255, 251, 246));
        tipoUsuarioRegistro.add(admin);
        admin.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(51, 51, 51));
        admin.setText("Administrador");
        REG.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        Register.setBackground(new java.awt.Color(255, 251, 246));
        Register.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Register.setForeground(new java.awt.Color(51, 51, 51));
        Register.setText("Registrarse");
        REG.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 107, 41));

        Cleaner.setBackground(new java.awt.Color(255, 251, 246));
        Cleaner.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Cleaner.setForeground(new java.awt.Color(51, 51, 51));
        Cleaner.setText("Limpiar");
        Cleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanerActionPerformed(evt);
            }
        });
        REG.add(Cleaner, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 87, 41));

        RWarning.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        RWarning.setForeground(new java.awt.Color(204, 0, 0));
        REG.add(RWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 160, 22));

        jLabel9.setBackground(new java.awt.Color(255, 251, 246));
        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Registrar");
        REG.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar.png"))); // NOI18N
        REG.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 350, 540));

        jTabbedPane1.addTab("Registrarse", REG);

        jPanel1.setBackground(new java.awt.Color(255, 251, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Path.setBackground(new java.awt.Color(255, 251, 246));
        Path.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Path.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Path, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 430, 30));

        jLabel6.setBackground(new java.awt.Color(255, 251, 246));
        jLabel6.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ingresar el Directorio Donde se Almacenan los datos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        SendPath.setBackground(new java.awt.Color(255, 251, 246));
        SendPath.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        SendPath.setForeground(new java.awt.Color(51, 51, 51));
        SendPath.setText("Enviar");
        SendPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendPathActionPerformed(evt);
            }
        });
        jPanel1.add(SendPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 90, 34));

        Messenger.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.add(Messenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 212, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/directory.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, 100));

        jTabbedPane1.addTab("Directorio", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // limpiar las casillas
        ID.setText("");
        name.setText("");
    }//GEN-LAST:event_CleanActionPerformed

    private void CleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanerActionPerformed
        // limpiar casillas de registro de sesion
        RID.setText("");
        Rname.setText("");
    }//GEN-LAST:event_CleanerActionPerformed

    private void SendPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SendPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clean;
    private javax.swing.JButton Cleaner;
    private javax.swing.JTextField ID;
    private javax.swing.JPanel LOG;
    private javax.swing.JButton Login;
    private javax.swing.JLabel LoginWarner;
    private javax.swing.JLabel Messenger;
    private javax.swing.JTextField Path;
    public javax.swing.JPanel REG;
    private javax.swing.JTextField RID;
    private javax.swing.JLabel RWarning;
    private javax.swing.JButton Register;
    private javax.swing.JTextField Rname;
    private javax.swing.JButton SendPath;
    private javax.swing.JRadioButton admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name;
    private javax.swing.ButtonGroup tipoUsuarioRegistro;
    private javax.swing.JRadioButton user;
    // End of variables declaration//GEN-END:variables
public javax.swing.JButton Login(){//devuelve la clase del boton de inicio de sesión
    return Login; 
}
public String LoginData(){//devolver el valor de los campos presionados
    return String.join(":", name.getText(),ID.getText());
}
public void Warning(String w){//mostrar el error u mensaje al usario en la gui
    LoginWarner.setText(w);
}
public javax.swing.JButton Register(){//devuelve la clase del boton de registrar sesión
    return Register; 
}
public void RWarning(String a){//mostrar el error u mensaje al usario en la gui en la pestaña de registro
    RWarning.setText(a);
}
public String[] NewUser(){//devuelve el array con los datos del nuevo usuario
    String[] data = new String[3];
    if(admin.isSelected()){//si se eleigio que sea administrador
        data[2] = String.valueOf(true);//true = administrador
    }else if(user.isSelected()){
        data[2] = String.valueOf(false);//false = usuario normal
    }
    data[0] = Rname.getText();//obtener valor de su nombre
    data[1]= RID.getText();//obtener valor de su ID
    
    return data;
}
public String getPath(){//obtener el directorio
    return Path.getText();
}
public javax.swing.JButton getSend(){//obtener la instancia del botón, le sirve al controlador
    return SendPath; 
}
public void setMessenger(String a){//advertencia o mensaje en el apartado de enviar directorio
    Messenger.setText(a);
}
}

