/*
Clase encargada de la interaccion en el menu de acciones
es decir la bista en sí
 */
package Vistas;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Bryan
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Selection = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        Obtener = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Recurso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Input = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        Admin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Load = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        deleteB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        Path = new javax.swing.JTextField();
        Warner = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 251, 246));
        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Seleccionar Recurso:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 220, 30));

        Selection.setBackground(new java.awt.Color(255, 251, 246));
        Selection.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Selection.setForeground(new java.awt.Color(51, 51, 51));
        Selection.setToolTipText("");
        jPanel1.add(Selection, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 30));

        Output.setBackground(new java.awt.Color(255, 251, 246));
        Output.setColumns(20);
        Output.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Output.setForeground(new java.awt.Color(51, 51, 51));
        Output.setRows(5);
        jScrollPane4.setViewportView(Output);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, 290));

        jLabel6.setBackground(new java.awt.Color(255, 251, 246));
        jLabel6.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Contenido: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        Obtener.setBackground(new java.awt.Color(255, 251, 246));
        Obtener.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Obtener.setForeground(new java.awt.Color(51, 51, 51));
        Obtener.setText("Obtener");
        jPanel1.add(Obtener, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        Refresh.setBackground(new java.awt.Color(255, 251, 246));
        Refresh.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Refresh.setForeground(new java.awt.Color(51, 51, 51));
        Refresh.setText("Refrescar");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recursos.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 380, 400));

        jTabbedPane1.addTab("Selección", jPanel1);

        Recurso.setBackground(new java.awt.Color(255, 251, 246));
        Recurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Escribe la capacitación:");
        Recurso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, -1));

        Save.setBackground(new java.awt.Color(255, 255, 255));
        Save.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Save.setForeground(new java.awt.Color(51, 51, 51));
        Save.setText("Aceptar");
        Save.setToolTipText("");
        Recurso.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 110, 40));

        Input.setBackground(new java.awt.Color(255, 251, 246));
        Input.setColumns(20);
        Input.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Input.setForeground(new java.awt.Color(0, 0, 0));
        Input.setRows(5);
        Input.setText("Escribir contenido aquí (por el momento no guarda el contenido) ");
        jScrollPane3.setViewportView(Input);

        Recurso.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 610, 190));

        jLabel8.setBackground(new java.awt.Color(255, 251, 246));
        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Crear Capacitación:");
        Recurso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        Recurso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/capacitacion.png"))); // NOI18N
        Recurso.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 440, 170));

        jTabbedPane1.addTab("Recursos", Recurso);

        Admin.setBackground(new java.awt.Color(255, 251, 246));
        Admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 251, 246));
        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Directorio del Recurso:");
        Admin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));

        jLabel4.setBackground(new java.awt.Color(255, 251, 246));
        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Borrar Recurso:");
        Admin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 126, -1));

        Load.setBackground(new java.awt.Color(255, 251, 246));
        Load.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Load.setForeground(new java.awt.Color(51, 51, 51));
        Load.setText("Cargar");
        Admin.add(Load, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 98, 40));

        Delete.setBackground(new java.awt.Color(255, 251, 246));
        Delete.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(51, 51, 51));
        Delete.setText("Borrar");
        Admin.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 101, 40));

        deleteB.setBackground(new java.awt.Color(255, 251, 246));
        deleteB.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        deleteB.setForeground(new java.awt.Color(102, 102, 102));
        Admin.add(deleteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 303, 35));

        jLabel5.setBackground(new java.awt.Color(255, 251, 246));
        jLabel5.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre del Recurso:");
        Admin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, -1));

        name.setBackground(new java.awt.Color(255, 251, 246));
        name.setForeground(new java.awt.Color(0, 0, 0));
        Admin.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 303, 30));

        Path.setBackground(new java.awt.Color(255, 251, 246));
        Path.setForeground(new java.awt.Color(0, 0, 0));
        Admin.add(Path, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 303, 30));
        Admin.add(Warner, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 200, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 251, 246));
        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Administración:");
        Admin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/a.png"))); // NOI18N
        Admin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 330, 410));

        jTabbedPane1.addTab("Administración", Admin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JButton Delete;
    private javax.swing.JTextArea Input;
    private javax.swing.JButton Load;
    public javax.swing.JButton Obtener;
    public javax.swing.JTextArea Output;
    private javax.swing.JTextField Path;
    private javax.swing.JPanel Recurso;
    public javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    public javax.swing.JComboBox<String> Selection;
    public javax.swing.JLabel Warner;
    private javax.swing.JComboBox<String> deleteB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

public String[] getNew(){//obtener array de datos del nuevo curso
    String d[] = new String[2]; 
    d[0] = name.getText();
    d[1] = Path.getText();
    return d; 
}
public javax.swing.JButton getLoad(){
    return Load; 
}
public void setOptions(ArrayList<String> a){//colocar todos los cursos disponibles
    a.forEach(option -> Selection.addItem(option) );
}

public void SetOutput(FileReader r){//recibir el archivo y mostrar su contenido
    try{
    BufferedReader rw = new BufferedReader(r);
    String line;
    while((line = rw.readLine() )!= null){
    Output.append(line +"\n");
    }
    }catch(IOException x){
        Output.setText("NO SE PUDO CARGAR EL ELEMENTO");
    }
}

}
