/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author inmar
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoUsuarioRegistro = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        LOG = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        LoginWarner = new javax.swing.JLabel();
        REG = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Rname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RID = new javax.swing.JTextField();
        user = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        Register = new javax.swing.JButton();
        Cleaner = new javax.swing.JButton();
        RWarning = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Path = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SendPath = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login.setText("Inicio de Sesion");

        Clean.setText("Limpiar");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar Nombre");

        jLabel2.setText("Ingresar ID Personal");

        LoginWarner.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout LOGLayout = new javax.swing.GroupLayout(LOG);
        LOG.setLayout(LOGLayout);
        LOGLayout.setHorizontalGroup(
            LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(name)
                        .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(LoginWarner))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LOGLayout.setVerticalGroup(
            LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LOGLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(LoginWarner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Clean)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Inicio Sesion", LOG);

        jLabel3.setText("Ingresar Nombre");

        jLabel4.setText("Ingresar ID Personal");

        tipoUsuarioRegistro.add(user);
        user.setText("Empleado");

        tipoUsuarioRegistro.add(admin);
        admin.setText("Administrador");

        Register.setText("Registrarse");

        Cleaner.setText("Limpiar");
        Cleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanerActionPerformed(evt);
            }
        });

        RWarning.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout REGLayout = new javax.swing.GroupLayout(REG);
        REG.setLayout(REGLayout);
        REGLayout.setHorizontalGroup(
            REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(REGLayout.createSequentialGroup()
                        .addGroup(REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(Rname)
                            .addComponent(jLabel4)
                            .addComponent(RID, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(RWarning))
                    .addComponent(user)
                    .addComponent(admin)
                    .addGroup(REGLayout.createSequentialGroup()
                        .addComponent(Register)
                        .addGap(18, 18, 18)
                        .addComponent(Cleaner)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        REGLayout.setVerticalGroup(
            REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RWarning))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(RID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin)
                .addGap(18, 18, 18)
                .addGroup(REGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register)
                    .addComponent(Cleaner))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrarse", REG);

        jLabel6.setText("Ingresar el Directorio Donde se Almacenan los datos");

        SendPath.setText("enviar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SendPath)
                    .addComponent(Path, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SendPath)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Directorio", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // limpiar las casillas
        ID.setText("");
        name.setText("");
    }//GEN-LAST:event_CleanActionPerformed

    private void CleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanerActionPerformed
        // limpiar casillas de registro de sesion
        RID.setText("");
        Rname.setText("");
    }//GEN-LAST:event_CleanerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clean;
    private javax.swing.JButton Cleaner;
    private javax.swing.JTextField ID;
    private javax.swing.JPanel LOG;
    private javax.swing.JButton Login;
    private javax.swing.JLabel LoginWarner;
    private javax.swing.JTextField Path;
    public javax.swing.JPanel REG;
    private javax.swing.JTextField RID;
    private javax.swing.JLabel RWarning;
    private javax.swing.JButton Register;
    private javax.swing.JTextField Rname;
    private javax.swing.JButton SendPath;
    private javax.swing.JRadioButton admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name;
    private javax.swing.ButtonGroup tipoUsuarioRegistro;
    private javax.swing.JRadioButton user;
    // End of variables declaration//GEN-END:variables
public javax.swing.JButton Login(){//devuelve la clase del boton de inicio de sesión
    return Login; 
}
public String LoginData(){//devolver el valor de los campos presionados
    return String.join(":", ID.getText(),name.getText());
}
public void Warning(String w){//mostrar el error u mensaje al usario en la gui
    LoginWarner.setText(w);
}
public javax.swing.JButton Register(){//devuelve la clase del boton de registrar sesión
    return Register; 
}
public void RWarning(String a){//mostrar el error u mensaje al usario en la gui en la pestaña de registro
    RWarning.setText(a);
}
public String[] NewUser(){//devuelve el array con los datos del nuevo usuario
    String[] data = new String[3];
    if(admin.isSelected()){//si se eleigio que sea administrador
        data[2] = String.valueOf(true);//true = administrador
    }else if(user.isSelected()){
        data[2] = String.valueOf(false);//false = usuario normal
    }
    data[0] = Rname.getText();//obtener valor de su nombre
    data[1]= RID.getText();//obtener valor de su ID
    
    return data;
}
}

